language: node_js
node_js: 
  - "stable"
branches:
  only:
  - master
stages:
  - test
cache:
  directories:
    - node_modules/
test:
  stage: test
  image: beevelop/nodejs-python
  variables:
    DB_URL: "mongodb://mongo/meatapi"
  services:
    - docker
    - mongodb
  script:
    - npm i
    - npm test