language: node_js
stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: beevelop/nodejs-python
  variables:
    DB_URL: "mongodb://mongo/meatapi"
  services:
    - docker
    - mongodb
  script:
    - npm i
    - npm test